/**********************************************************************
*
*   Component hook generated by Quest
*
*   Code Logic for the component goes in this hook
*   To setup bindings that use the data here or call the functions here, use the Quest editor   
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

const useFrame4 = () => {
  
  let data: any = { };
  const algo = (param1: any): any => {};

  let fns: any = {algo};
  return {data, fns};
}

export default useFrame4;