/**********************************************************************
*
*   Component hook generated by Quest
*
*   Code Logic for the component goes in this hook
*   To setup bindings that use the data here or call the functions here, use the Quest editor   
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/
import {data, fns} from './other-hook';
const useFrame4 = () => {
  
  return {data, fns};
}

export default useFrame4;
  const algo = (param1: any): any => {};
