/**********************************************************************
*
*   Component hook generated by Quest
*
*   Code Logic for the component goes in this hook
*   To setup bindings that use the data here or call the functions here, use the Quest editor   
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/
import useAlgo = form './useOtherHook';

const useFrame4 = () => {
  

  const chau = (param1: any): any => {};
//  let fns: any = {algo, chau};
  const { data, fns} = useAlgo();
  return {data, fns};
}

export default useFrame4;
